### PR TITLE
Overhaul configuration loading

### LINKED ISSUE #36: project-config command line option does not work
It appears that the `--project-config` option is not effective. When specified:

1. The project config is still read from the current working directory
2. If the file specified with `--project-config` does not exist, no error is thrown, even though looking at the code it should throw an error

This might be caused by the configuration now being loaded in `di.php` while the `--project-config` option is only processed in `\Meanbee\Magedbm2\Application::loadProjectConfig`.

### PR DESCRIPTION
**Pull request by punkstar**
The loading of the configuration was messy with the ability to override file based configuration with parameters when called with command options. This has caused race conditions due to the configuration files themselves) being able to be overridden with an option too.

Unfortunately @Quintenps's approach switch the ordering of the arguments was a band aid for the bigger architectural problem.

- Move the parsing and loading of configuration from the base Application class to just before the command is executed, giving time for all inputs to be read and configuration overwritten, if required.

- Reduce the responsibility of the S3 client to specify options, and bundle those options into the global options list.

- Redo the configure command to allow for the specification of a file to write to.

Fixes #36.

### CODE REVIEW

File: src/Command/BaseCommand.php [hunk 1]
```diff
@@ -146,4 +265,71 @@ private function loadAdditionalConfig()
...
+    /**
+     *
+     *
+     * @param $argvFileName
+     * @param $fallbackFileName
+     * @throws ConfigurationException
+     */
+    private function tryConfigLoadFromFiles($argvFileName, $fallbackFileName)
+    {
+        $canError = false;
```
Comment (tgerulaitis) [inline src/Command/BaseCommand.php]: Looks like this is never set to `true` in this function.
